### PR TITLE
#1904 landing page post order select field throwing error when adding new lp

### LINKED ISSUE #1904: landing page post order select field throwing error when adding new LP
## Expected Behavior
Post order field should load and work as any select field would

## Actual Behavior
Select field does not show up
Fatal error: Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, bool given in /largo/wp-content/themes/largo/inc/wp-taxonomy-landing/functions/cftl-admin.php on line 450

## Steps to Reproduce the Problem

  1. Pull down trunk branch and try to create a new landing page, note this is on a fresh install no DB data at all, zero content!!!
  2. in the Main section where post order field should be the error above is shown

## Specifications

  - Version: php@7.4.16
  - Platform: MacOS using Valet to run local
  - image provided
Screen Shot 2021-04-11 at 12 07 42 PM

### PR DESCRIPTION
**Pull request by rlambertsen**
## Changes

This pull request makes the following changes:

landing page post order select field throwing error when adding new lp the variable is sometimes false; need to make sure we check for that first

## Why
The select field for post order does not show up
For #1904 

## Testing/Questions
Pull fresh largo branch trunk down and have zero data on the site. Try to create a Landing Page
Features that this PR affects:

- Creating LP's

Questions that need to be answered before merging:

- [x] Is this PR targeting the correct branch in this repository?
- [] Has the `changelog.md` file been updated to reflect the updates in this PR?
- [ ] 

Steps to test this PR:

1. 

## Additional information

WP Buddy Client requesting: (if applicable)

- [ ] Contributor has read WP Buddy's [GitHub code of conduct](https://github.com/WPBuddy/.github/blob/master/CODE_OF_CONDUCT.md)
- [ ] Contributor would like to be mentioned in the release notes as: (fill in this blank)
- [ ] Contributor agrees to the license terms of this repository.

### CODE REVIEW

File: inc/wp-taxonomy-landing/functions/cftl-admin.php [hunk 1]
```diff
@@ -447,7 +447,17 @@ function cftl_tax_landing_main($post) {
 		<?php
 			//allow 'custom' if we have a single term
 			$terms = get_the_terms( $post->ID, 'series');
-			if (count($terms) == 1) $series_id = $terms[0]->term_taxonomy_id;
+			/*
+            * issue #1904
+            * when trying to check the count of false we get an error
+            * check its not false and is and array before trying to count it
+            */
+            $terms = get_the_terms( $post->ID, 'series');
```
Comment (joshdarby) [inline inc/wp-taxonomy-landing/functions/cftl-admin.php]: @rlambertsen a few things:
- can you fix the spacing here?
- `$terms` is defined twice. Once at 449 then again at 455
- add another space at after `'series'`;

File: inc/wp-taxonomy-landing/functions/cftl-admin.php [hunk 2]
```diff
@@ -447,7 +447,17 @@ function cftl_tax_landing_main($post) {
...
+            if ($terms && is_array($terms) && count($terms) == 1) {
```
Comment (joshdarby) [inline inc/wp-taxonomy-landing/functions/cftl-admin.php]: @rlambertsen can you make to sure add spacing here between the arguments and the `( )`?

Also, we'll probably want to make `count($terms) == 1` into `count( $terms ) >= 0` because it's possible that there will be more than one

**Review by joshdarby — CHANGES_REQUESTED** [review]

File: inc/wp-taxonomy-landing/functions/cftl-admin.php (hunk 2 above)
Comment (rlambertsen) [reply inc/wp-taxonomy-landing/functions/cftl-admin.php]: has to be greater than or equal to 1 if. IF zero it will be false and wont get that far

**Comment by joshdarby** [comment]
@rlambertsen This looks good. Just fix the spacing issues and it'll be good to go.
