### PR TITLE
#1540 update grunt dependencies

### LINKED ISSUE #1540: Update Grunt dependencies
In package.json, update everything to the latest version, then run all the grunt tasks to see what's broken. Then fix.

### PR DESCRIPTION
**Pull request by rlambertsen**
## Changes

This pull request makes the following changes:

- Update Grunt dependencies to latest versions
- add package.json lock file to keep npm packages locked to our versions we push
- Update change-log with changes
- build process for grunt was changed to allow developers to run separate commands 

## Why

For #1540

## Testing/Questions

Features that this PR affects:

- Development work flow

Questions that need to be answered before merging:

- [x] Is this PR targeting the correct branch in this repository?
- [x] Has the `changelog.md` file been updated to reflect the updates in this PR?

Steps to test this PR:

1.  Just pull down, merge changes, package.json should have latest versions (see this branches package.json)

## Additional information

WP Buddy Client requesting: (if applicable)

- [x] Contributor has read WP Buddy's [GitHub code of conduct](https://github.com/WPBuddy/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] Contributor would like to be mentioned in the release notes as: admin
- [x] Contributor agrees to the license terms of this repository.

### CODE REVIEW

File: Gruntfile.js [hunk 1]
```diff
@@ -170,14 +170,18 @@ module.exports = function(grunt) {
   // Former grunt-pot
   grunt.registerTask('pot', ['shell:pot']);
 
-  // Build assets, docs and language files
-  grunt.registerTask('build', 'Build assets, docs and language files', [
-    'less',
-    'cssmin',
-    'uglify',
```
Comment (benlk) [inline Gruntfile.js]: I don't disagree with making a separate `UI` task to separately run the less/cssmin/uglify items. It's nice to be able to run those separately. 

But whether or not that's done, these items should remain within the `build` task so that the release process remains as simple as possible: https://github.com/WPBuddy/largo/issues/1798

**Review by joshdarby — APPROVED** [review]
